# Site settings
title: CPS Public Working Group
description: "The Cyber-Physical Systems Public Working Group (CPS PWG) will bring together experts to help define and shape key aspects of CPS to accelerate its development and implementation within multiple sectors of our economy."

baseurl: "/cpspwg"
rooturl: ""

# Build settings
markdown: kramdown
permalink: pretty
exclude: [node_modules, gruntfile.js, package,json]
